apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-deployment-access
subjects:
  - kind: Group
    name: jenkins-deployment-group
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: jenkins-deployment-access
  apiGroup: rbac.authorization.k8s.io
